version: 2
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: 2_column_-_right
  timestamp: 1508332860
layout:
  header: {  }
  navigation: {  }
  /container-main/:
    -
      -
        'main 75': {  }
      -
        'sidebar 25':
          -
            - location-search-8711
  footer: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  main:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  location-search-8711:
    title: 'Location Search'
    attributes:
      title: 'Find Your''s'
      path: '/?post_type=indv_politician'
