version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1508332860
layout:
  /header/:
    -
      - 'logo-3261 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-9521
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-1237
    -
      - system-content-8793
  /footer/:
    -
      - position-footer
    -
      - 'copyright-3374 40'
      - 'spacer-4288 30'
      - 'branding-7003 30'
  offcanvas:
    -
      - mobile-menu-4002
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
