query posts($id: ID) {
  organization(id: $id) {
    name
    classification
    links {
      note
      url
    }
    sources {
      note
      url
    }
    members: currentMemberships {
      id
      person {
        id
        name
        familyName
        givenName
        image
        contactDetails {
          type
          value
          note
          label
        }
        links {
          note
          url
        }
        sources {
          note
          url
        }
        identifiers {
          scheme
          identifier
        }
        updatedAt
      }
      post {
        id
        role
        label
        division {
          id
          name
        }
      }
    }
  }
}
