query posts($id: ID) {
  organization(id: $id) {
    id
    name
    classification
    links {
      note
      url
    }
    sources {
      note
      url
    }
    members: currentMemberships {
      person {
        id
        name
        image
        contact: contactDetails {
          type
          value
          note
          label
        }
        party: currentMemberships (classification: "party") {
          organization {
            name
          }
        }
        committees: currentMemberships(classification: "committee") {
          organization {
            name
            parent {
              name
            }
          }
        }
        links {
          note
          url
        }
        sources {
          note
          url
        }
        identifiers {
          scheme
          identifier
        }
      }
      post {
        id
        role
        label
        division {
          id
          name
        }
      }
    }
  }
}
