name: React Element
description: Render a React element in a DOM element obtained by ID.
type: particle

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable to the particles.
      default: true

    title:
      type: input.text
      label: Title
      description: Customize the section title text.   

    selector:
      type: input.text
      label: Selector
      description: The selector id for the target element.

    class:
      type: input.text
      label: Class
      description: The class of the React component.

    props:
      type: collection.list
      array: true
      label: Properties
      description: Properties passed to the constructor.
      value: name
      ajax: true

      fields:
        .name:
          type: input.text
          label: Name.
          description: The property name.

        .value:
          type: textarea.text
          label: Value

        .description:
          type: textarea.textarea
          label: Description

    library:
      type: collection.list
      array: true
      label: Library
      description: JavaScript library to load.
      value: url
      ajax: true

      fields:
        .url:
          type: input.url
          label: URL
