version: 2
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: 2_column_-_right
  timestamp: 1508332860
layout:
  header: {  }
  navigation: {  }
  /container-main/:
    -
      -
        'main 75':
          -
            - system-content-4583
      -
        'sidebar 25':
          -
            - position-widget-4707
          -
            - position-widget-3855
  footer: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  sidebar:
    type: section
    subtype: aside
    block:
      fixed: 1
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  position-widget-4707:
    attributes:
      widget: '{"type":"widget","widget":"twitter-timeline-profile","title":"Twitter Profile","options":{"widget":{"tweet-limit":5,"screen_name":"CAStateStrong","limit":5}}}'
  position-widget-3855:
    attributes:
      widget: '{"type":"widget","widget":"meta","title":"Meta","options":{"widget":{"title":""}}}'
      key: widget
