name: sidebar
timestamp: 1519594887
version: 7
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: 2_column_-_right
  timestamp: 1508332860
positions: {  }
sections:
  header: Header
  navigation: Navigation
  main: Main
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  widget:
    position-widget-4707: Widget
    position-widget-9609: Widget
  messages:
    system-messages-1263: 'System Messages'
  logo:
    logo-5779: 'Logo / Image'
  menu:
    menu-8097: Menu
  content:
    system-content-4676: 'Page Content'
  copyright:
    copyright-7517: Copyright
  social:
    social-1100: Social
  branding:
    branding-4493: Branding
  mobile-menu:
    mobile-menu-9609: Mobile-menu
inherit:
  default:
    header: header
    navigation: navigation
    main: main
    footer: footer
    offcanvas: offcanvas
    system-messages-1263: system-messages-4735
    logo-5779: logo-7296
    menu-8097: menu-6948
    system-content-4676: system-content-3116
    position-widget-9609: position-widget-1625
    copyright-7517: copyright-6921
    social-1100: social-8965
    branding-4493: branding-3800
    mobile-menu-9609: mobile-menu-1056
